# Groq API Key (get from console.groq.com)
GROQ_API_KEY = ""

# OpenAI API Key (get from platform.openai.com)
OPENAI_API_KEY = ""

# OpenRouter API Key (get from openrouter.ai)
OPENROUTER_API_KEY = ""
