# Groq API Key (get from console.groq.com)
GROQ_API_KEY = "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"

# OpenAI API Key (get from platform.openai.com)
OPENAI_API_KEY = "your_openai_api_key_here"

# OpenRouter API Key (get from openrouter.ai)
OPENROUTER_API_KEY = "your_openrouter_api_key_here"